# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  - name: elm-version
    value: 0.19.1
  - group: GitHub
  - name: GitHubPAT
    value: $[variables.GitHubPAT]

trigger:
  branches:
    include:
    - master
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
    - job:
      displayName: install dependencies
      steps:
      - bash: |
          if [ ! -d libsysconfcpus ]; then git clone https://github.com/obmarg/libsysconfcpus.git; fi
          cd libsysconfcpus && ./configure && make && sudo make install
      - bash: |
          if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
            curl -o- -L https://yarnpkg.com/install.sh | bash -s
          fi
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      - bash: |
          curl -L -o elm.gz "https://github.com/elm/compiler/releases/download/$(elm-version)/binary-for-linux-64-bit.gz"
          gunzip elm.gz
          sudo chmod +x elm
          sudo mv elm /usr/local/bin
          export PATH="/usr/local/bin:$PATH"
    - job:
      displayName: build static web artifact
      steps:
      - bash: |
          yarn global add create-elm-app 
          sudo chmod +x $HOME/.yarn/bin
          elm make src/Main.elm --optimize --output=main.js
          elm-app build
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/build
          artifactName: WebApp
      - bash: |
          cd build
          git checkout pages
          git add .
          git commit -m "update gh pages"
          git push 


